[tool.poetry]
name = "smartnoise-sql"
version = "0.2.0.dev0"
description = "Differentially Private SQL Queries"
authors = ["SmartNoise Team <smartnoise@opendp.org>"]
license = "MIT"
packages = [{include="snsql"}]
homepage = "https://smartnoise.org"
repository = "https://github.com/opendp/smartnoise-sdk"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1,<=3.9"
antlr4-python3-runtime = "4.8"
opendp = "^0.3.0"
pandasql = "^0.7.3"
numpy = "^1.21.2"
PyYAML = "^5.4.1"
pandas = "^1.3.3"
graphviz = "^0.17"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
