name: SQL on Pandas

on:
  pull_request:
    paths:
      - 'sql/tests/**'
      - 'sql/snsql/**'
      - 'sql/pyproject.toml'
      - '!sql/tests/setup/postgres/**'
      - '!sql/tests/setup/sqlserver/**'
      - '!sql/tests/setup/mysql/**'
      - '!sql/tests/setup/biqquery/**'
  workflow_dispatch:

jobs:
  sql-pandas-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      shell: bash -l {0}
      run: |
        conda install pip
        conda update pip
    - name: Install smartnoise-sql
      shell: bash -l {0}
      run: |
        cd sql
        pip install --no-cache-dir .
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        cd sql
        pip install --no-cache-dir -r tests/requirements.txt
    - name: Test SDK
      shell: bash -l {0}
      run: |
        cd sql
        pytest tests
